/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fbf8ff",
        "error": "#ba1a1a",
        "on-surface-variant": "#444652",
        "tertiary": "#400500",
        "error-container": "#ffdad6",
        "surface-variant": "#e3e1ea",
        "surface-container-high": "#e9e7f0",
        "primary": "#001359",
        "surface-tint": "#3f56ba",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2f3037",
        "on-surface": "#1a1b22",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffdad3",
        "secondary-container": "#00ccf9",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#001f28",
        "on-tertiary-fixed-variant": "#832514",
        "on-secondary-fixed-variant": "#004e60",
        "surface-container-highest": "#e3e1ea",
        "on-error": "#ffffff",
        "primary-container": "#00238c",
        "surface-dim": "#dad9e2",
        "tertiary-container": "#650f02",
        "background": "#fbf8ff",
        "inverse-on-surface": "#f1f0f9",
        "on-primary-fixed": "#001257",
        "surface-container-low": "#f4f2fc",
        "outline-variant": "#c5c5d5",
        "outline": "#757684",
        "on-primary-fixed-variant": "#243ca1",
        "surface-container": "#eeedf6",
        "primary-fixed-dim": "#b9c3ff",
        "on-background": "#1a1b22",
        "secondary-fixed-dim": "#4cd6ff",
        "tertiary-fixed-dim": "#ffb4a5",
        "primary-fixed": "#dde1ff",
        "on-primary-container": "#7d92fb",
        "inverse-primary": "#b9c3ff",
        "secondary": "#00677f",
        "on-tertiary-container": "#f0755c",
        "secondary-fixed": "#b7eaff",
        "on-secondary-container": "#005266",
        "surface": "#fbf8ff",
        "on-tertiary-fixed": "#3e0400"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
